routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeControler;
use App\Http\Controllers\PostController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeControler::class, 'index'])->name('user.index');
Route::get('/create', [HomeControler::class, 'create'])->name('user.create');
Route::post('/store', [HomeControler::class, 'store'])->name('user.store');
Route::get('/edit/{id}', [HomeControler::class, 'edit'])->name('user.edit');
Route::post('/update/{id}', [HomeControler::class, 'update'])->name('user.update');
Route::delete('/delete/{id}', [HomeControler::class, 'delete'])->name('user.delete');

Route::resource('posts', PostController::class);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'user_id'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'phone_no',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeControler.php
<?php

namespace App\Http\Controllers;
use App\Models\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class HomeControler extends Controller
{
    public function index() 
    {
        // $users = User::with('posts');
        $users = User::all();
        // dd($user->posts);
        // foreach($user->posts as $post){
        //     dd($post->title);
        // }
        // $post->user->name;
        return view('index', compact('users'));
    }

    public function create()
    {
        return view('create');
    }

    public function store(Request $request)
    {
       $data = $request->validate([
            'name' => ['required'],
            'email' => ['required'],
            'password' => ['required', 'min:5', 'max:15'],
            'phone_no' => ['required']
        ],
        [
            'name.required' => 'နာမည်ဖြည့်သွင်းရန်လိုအပ်ပါသည်။'
        ]
    );
    // $data['password'] = Hash::make($request->password);
    // $user = new User();
    // $user->name =  $request->name;
    // $user->email = $request->email;
    // $user->password =  Hash::make($request->password);
    // $user->phone_no = $request->phone_no;
    // $user->save();

    User::create($data);

    return redirect()->route('user.index')->with('success', 'Successfully Created!');

    }

    public function edit($id)
    {
        // $user = User::where('id', $id);
        $user = User::findOrFail($id);

        return view('edit', compact('user'));
    
    }

    public function update(Request $request, $id)
    {
        // dd($id);
        $user = User::findOrFail($id);
        $data = $request->validate([
            'name' => ['required'],
            'email' => ['required'],
            'password' => ['nullable'],
            'phone_no' => ['required']
        ],
        [
            'name.required' => 'နာမည်ဖြည့်သွင်းရန်လိုအပ်ပါသည်။'
        ]
        );

        if($request->password){
            $data['password'] = Hash::make($request->password);
        } else {
            $data['password'] = $user->password;
        }
        // dd($data['password']);
        $user->update($data);

        return redirect()->route('user.index')->with('success', 'Successfully Updated!');
    }

    public function delete($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('user.index')->with('success', 'Successfully Deleted');
        
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $posts = Post::all();
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $users = User::all();
        return view('posts.create', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'title' => ['required'],
            'description' => ['required'],
            'user_id' => ['required']
        ],
        [
            'user_id.required' => 'User Field is required'
        ]);

        Post::create($data);
        // $post = new Post();
        // $post->title = $request->title;
        // $post->description = $request->description;
        // $post->user_id = $request->user_id;
        // $post->save();

        return redirect()->route('posts.index')->with('success', 'Successfully Created!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Post $post)
    {
        //
    }
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>@yield('title')</title>
</head>
<body>
    @yield('content')
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

resources/views/create.blade.php
@extends('app')
@section('title', 'User Create')
@section('content')
    <div class="container mt-5">
        @if ($errors->any())
            @foreach ($errors->all() as $error)
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{ $error }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            @endforeach
        @endif
        
        <form method="POST" action="{{ route('user.store') }}">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" id="name" value="{{ old('name') }}">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" value="{{ old('email') }}">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="password">
            </div>
            <div class="form-group">
                <label for="phone_no">Phone No</label>
                <input type="number" name="phone_no" class="form-control" id="phone_no" value="{{ old('phone_no') }}">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/edit.blade.php
@extends('app')
@section('title', 'User Edit')
@section('content')
    <div class="container mt-5">
        @if ($errors->any())
            @foreach ($errors->all() as $error)
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{ $error }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            @endforeach
        @endif
        
        <form method="POST" action="{{ route('user.update', $user->id) }}">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" id="name" value="{{ $user->name }}">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" value="{{ $user->email }}">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="password">
            </div>
            <div class="form-group">
                <label for="phone_no">Phone No</label>
                <input type="number" name="phone_no" class="form-control" id="phone_no" value="{{ $user->phone_no }}">
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
@endsection

resources/views/index.blade.php
@extends('app')
@section('title', 'User List')
@section('content')
<div class="container mt-5">
    @if(session('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Holy guacamole!</strong> {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    @endif
   <div class="d-flex justify-content-between">
    <h1>Users</h1>
    <a href="{{ route('user.create') }}">Creat New</a>
   </div>
    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    @php
    $i = 1;
    @endphp
    @foreach($users as $user)
    <tr>
      <th scope="row">{{ $i++ }}</th>
      <td>{{ $user->name }}</td>
      <td>{{ $user->email}}</td>
      <td>{{ $user->phone_no }}</td>
      <td>
        {{-- <a href="{{ url('edit/'.$user->id) }}">Edit</a> --}}
        <a href="{{ route('user.edit', $user->id) }}">Edit</a>
        <form action="{{ route('user.delete', $user->id) }}" method="POST">
            @csrf
            @method('DELETE')
            <button type="submit">Delete</button>

        </form>
      </td>
    </tr>
    @endforeach
  </tbody>
</table>
   </div>
@endsection

resources/views/posts/create.blade.php
@extends('app')
@section('title', 'User Create')
@section('content')
    <div class="container mt-5">
        @if ($errors->any())
            @foreach ($errors->all() as $error)
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Holy guacamole!</strong> {{ $error }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endforeach
        @endif

        <form method="POST" action="{{ route('posts.store') }}">
            @csrf
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" name="title" class="form-control" id="title" value="{{ old('title') }}">
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <textarea class="form-control" name="description" id="description" rows="3"></textarea>
            </div>
            <div class="form-group">
                <label for="user">User</label>
                <select class="form-control" id="user" name="user_id">
                    <option value="">Select User</option>
                    @foreach ($users as $user)
                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                    @endforeach
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('app')
@section('title', 'Post List')
@section('content')
<div class="container mt-5">
    @if(session('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Holy guacamole!</strong> {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    @endif
   <div class="d-flex justify-content-between">
    <h1>posts</h1>
    <a href="{{ route('posts.create') }}">Creat New</a>
   </div>
    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">post</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    @php
    $i = 1;
    @endphp
    @foreach($posts as $post)
    <tr>
      <th scope="row">{{ $i++ }}</th>
      <td>{{ $post->title }}</td>
      <td>{{ $post->description}}</td>
      <td>{{ $post->user->name }}</td>
      <td>
        {{-- <a href="{{ url('edit/'.$post->id) }}">Edit</a> --}}
        {{-- <a href="{{ route('posts.edit', $post->id) }}">Edit</a>
        <form action="{{ route('posts.delete', $post->id) }}" method="POST">
            @csrf
            @method('DELETE')
            <button type="submit">Delete</button>

        </form> --}}
      </td>
    </tr>
    @endforeach
  </tbody>
</table>
   </div>
@endsection